# fly.toml app configuration file generated for mundinovi2024 on 2024-08-21T16:30:12-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mundinovi2024'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
