const mongoose = require('mongoose');
const { Schema } = mongoose;

const productoSchema = new Schema({
  clave: { type: String, required: true },
  claveAlterna: { type: String },
  codigoBarras: { type: String },
  nombre: { type: String, required: true },
  descripcion: { type: String },
  fechaAlta: { type: Date, default: Date.now },
  claveProductosSAT: { type: String },
  estado: { type: Boolean, default: true },
  esKit: { type: Boolean, default: false },
  esGrupoDeProductos: { type: Boolean, default: false },
  categoria: { type: Schema.Types.ObjectId, ref: 'Categoria' },
  grupo: { type: Schema.Types.ObjectId, ref: 'Grupo' },
  marca: { type: Schema.Types.ObjectId, ref: 'Marca' },
  tipoDeProducto: { type: Schema.Types.ObjectId, ref: 'TipoDeProducto' },
  linea: { type: Schema.Types.ObjectId, ref: 'Linea' },
  departamento: { type: Schema.Types.ObjectId, ref: 'Departamento' },
  unidad: { type: Schema.Types.ObjectId, ref: 'Unidad' },
  impuesto: { type: Schema.Types.ObjectId, ref: 'Impuesto' },
  observaciones: { type: String },

  datosFinancieros: {
    tiempoDeSurtido: { type: Number },
    controlDeAlmacen: { type: Boolean },
    volumen: { type: Number },
    peso: { type: Number },
    stockMinimo: { type: Number },
    stockMaximo: { type: Number },
    costo: { type: Number },
    ultimoCosto: { type: Number },
    costoPromedio: { type: Number },
    numeroPrecioMinimo: { type: Number },
    numeroPrecioMaximo: { type: Number },
    presentacion: { type: String },
    porcentajePrecio1: { type: Number },
    porcentajePrecio2: { type: Number },
    porcentajePrecio3: { type: Number },
    porcentajePrecio4: { type: Number },
    porcentajePrecio5: { type: Number },
    porcentajePrecio6: { type: Number },
    porcentajePrecio7: { type: Number },
    porcentajePrecio8: { type: Number },
    porcentajePrecio9: { type: Number },
    porcentajePrecio10: { type: Number },
    precio1: { type: Number },
    precio2: { type: Number },
    precio3: { type: Number },
    precio4: { type: Number },
    precio5: { type: Number },
    precio6: { type: Number },
    precio7: { type: Number },
    precio8: { type: Number },
    precio9: { type: Number },
    precio10: { type: Number },
    rangoInicial1: { type: Number },
    rangoInicial2: { type: Number },
    rangoInicial3: { type: Number },
    rangoInicial4: { type: Number },
    rangoInicial5: { type: Number },
    rangoInicial6: { type: Number },
    rangoInicial7: { type: Number },
    rangoInicial8: { type: Number },
    rangoInicial9: { type: Number },
    rangoInicial10: { type: Number },
    rangoFinal1: { type: Number },
    rangoFinal2: { type: Number },
    rangoFinal3: { type: Number },
    rangoFinal4: { type: Number },
    rangoFinal5: { type: Number },
    rangoFinal6: { type: Number },
    rangoFinal7: { type: Number },
    rangoFinal8: { type: Number },
    rangoFinal9: { type: Number },
    rangoFinal10: { type: Number }
  },

  proveedores: [{ type: Schema.Types.ObjectId, ref: 'Proveedor' }],
  
  productosAdicionales: [{ type: Schema.Types.ObjectId, ref: 'Producto' }],

  productosComplementarios: [{ nombre: { type: String } }]
});

const Producto = mongoose.model('Producto', productoSchema);

module.exports = Producto;
